[package]
name = "discord-rust-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = { version = "0.11", features = ["client", "framework"] }
tokio = { version = "1", features = ["full"] }
chrono = "0.4"